# workflow for building and deploying a Nuxt.js site to GitHub Pages
#
#
name: Test Nuxt.js build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Runs on any open or reopened pull request
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PRISMA_DB_URL: "file:dev.db"
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/Iron"
          cache: npm
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci
      - name: Create Prisma Generator
        run: npx prisma generate --allow-no-models
      - name: Build with Nuxt.js
        run: npm run build
